web/app/(personal-run)/running-session/page.tsx
남은 거리 초과시 + 표시
1. 남은 거리 초과시 + 표시
/web/app/running-session/page.tsx
=> feat: 남은 거리 초과시 +표시

web/app/(personal-run)/lucky-stamp/page.tsx, web/app/(personal-run)/prepare-run/page.tsx, web/app/(personal-run)/start-count/page.tsx, web/app/globals.css, web/components/running/Control/StopConfirmModal.tsx, web/components/running/Finish/CircleProgress.tsx, web/components/running/OverView/MainOverview.tsx, web/components/running/OverView/StatCard.tsx
기본 글꼴 스타일을 lufga-> pretendard로 변경
=> chore:기본 폰트스타일 pretandard로 수정

web/app/onboarding/page.tsx
온보딩 화면 슬라이드 구현
1. 온보딩 화면 구현
``/web/app/onboarding/page.tsx``
=> feat: onboarding 슬라이드 구현

web/app/notification/page.tsx, web/components/main/MainHeader.tsx, web/components/notification/NotificationCard.tsx
알림화면 구현
``/web/notification/page.tsx``
=> feat:알림화면 구현

web/components/common/DecimalInput.tsx
decimalInput.tsx에 placeholder 없어서 setup-target/page.tsx에 오류 뜨던거 해결 
``/web/components/common/DecimalInput.tsx``
=> chore: placehoder props 추가

web/.gitignore, web/package.json
=> feat:개발환경 https 설정

web/app/group/code/[...code]/page.tsx, web/components/main/CrewChallengeCard.tsx, web/components/main/CrewChallengeSection.tsx
- CrewChallengeSection 더미데이터 추가
=> hotfix: CrewChallengeSection 수정

web/app/main/page.tsx, web/app/onboarding/terms/page.tsx
=> fix: 위치 main으로 수정

web/app/badge-collection/gacha/result/page.tsx, web/components/gacha/ResultPage.tsx
useSearchParam 오류 수정
서버 클라이언트 측에서 prerendering할때 useSearchParams은 클라이언트 컴포넌트에서만 사용할 수 있어서 에러
=> fix:useSearchParam 오류 수정

web/components/common/CloverCountChip.tsx
=> style: badge-collection에서 CloverCountChip.tsx 위치 수정

web/app/main/page.tsx
main에 테스트용 로그인 버튼 전송시 router import 에러 해결
=> fix:임시 로그인버튼 router import 추가

web/app/(personal-run)/run-finish/page.tsx, web/app/today-run-result/page.tsx, web/components/main/WeeklyGoalCard.tsx, web/components/running/Finish/CircleProgress.tsx
feat: 달리기 완료 후 circle progress 연결
오늘 달린 정보 보기 페이지 circle progress 삭제
=> feat: 달리기 완료 후 circle progress 연결 오늘 달린 정보 보기 페이지 circle progress 삭제

web/components/main/CheerCard/CheerCardWrapper.tsx, web/components/main/CheerCard/ManyActiveRunner.tsx, web/components/main/CheerCard/OneActiveRunner.tsx, web/components/main/CheerCard/TwoActiveRunner.tsx, web/types/runningUser.ts
=> feat: 달리고 있는 크루원 뱃지 이미지 추가

web/app/(personal-run)/run-finish/page.tsx
변경된 finishData 구조로 인한 표시 문제 해결
초기에 하나의 값만 담다가 하루 러닝 데이터 배열을 담으면서 생긴 문제 해결
``/web/app/(personal-run)/run-finish/page.tsx``
=> fix: 변경된 finishData 구조로 인한 표시 문제 해결

app/app/(tabs)/(group)/code/index.tsx, app/app/(tabs)/(group)/create/index.tsx, app/app/(tabs)/(group)/index.tsx, app/app/(tabs)/(group)/running/[id]/_layout.tsx, app/app/(tabs)/(group)/running/[id]/index.tsx, app/app/(tabs)/(group)/running/[id]/runningShare.tsx, app/app/(tabs)/(home)/index.tsx, app/app/(tabs)/(single-running)/index.tsx, app/app/(tabs)/_layout.tsx, app/components/ProgressBar.tsx, app/components/bottom-sheets/contents/EditGroupNotificationContent.tsx, app/components/bottom-sheets/contents/EditMemberContent.tsx, app/eas.json, app/hooks/useFetch.ts, app/types/crew.ts, app/utils/webView/index.ts, web/app/group/code/page.tsx, web/app/group/page.tsx, web/app/group/running/page.tsx, web/app/main/page.tsx, web/components/common/DefaultLayout.tsx, web/components/main/CrewChallengeCard.tsx, web/configs/groupRouteConfig.ts, web/types/crew.ts
- Web < -> App 라우팅 수정
- 유저 닉네임 asyncStorage 저장 로직 구현
- group api 수정 및 추가 데이터 연결
=> Group API 연결

web/app/calendar/page.tsx, web/components/calendar/Calendar.tsx, web/components/calendar/CalendarCells.tsx, web/components/calendar/CalendarDays.tsx, web/components/calendar/CalendarHeader.tsx, web/configs/routeConfig.ts, web/package-lock.json, web/package.json
=> feat:캘린더 UI 및 오늘 총 달린 거리 표시

web/app/today-run-result/page.tsx, web/components/googleMap/GoogleMap.tsx, web/components/today-run-result/TodayRunPage.tsx
=> fix:today-run-result 하단 여백 수정

app/app.config.js, app/app/(tabs)/(single-running)/index.tsx
=> feat: MOCK Location 삭제

web/app/(personal-run)/prepare-run/page.tsx, web/components/main/WeeklyGoalCard.tsx
=> feat: RN 페이지이동,RN 현재위치 받아오기

web/app/badge-collection/page.tsx, web/app/main/page.tsx, web/components/gacha/BadgeItem.tsx, web/components/gacha/BadgeList.tsx, web/components/main/WelcomeCard.tsx, web/utils/apis/api.ts
=> feat:뱃지 변경시 바로 적용

web/app/(personal-run)/prepare-run/page.tsx
=> feat: 한번더 message들어가기

web/components/gacha/BadgeItem.tsx
=> fix:ui 오류 수정

app/app/(tabs)/(group)/index.tsx, web/app/group/layout.tsx, web/app/group/page.tsx, web/configs/groupRouteConfig.ts
=> Web, App rotue config 수정

app/app/(tabs)/(group)/code/_layout.tsx, app/app/(tabs)/(group)/code/index.tsx, app/app/(tabs)/(group)/create/index.tsx, app/app/(tabs)/(group)/index.tsx, app/app/(tabs)/(group)/running/[id]/_layout.tsx, app/app/(tabs)/(group)/running/[id]/index.tsx, app/app/(tabs)/(group)/running/[id]/runningShare.tsx, app/app/(tabs)/(home)/index.tsx, app/app/(tabs)/(single-running)/index.tsx, app/app/(tabs)/_layout.tsx, app/components/bottom-sheets/contents/EditGroupNotificationContent.tsx, app/components/chips/Chip.tsx, app/components/containers/running/BottomSheetContainer.tsx, app/components/modal/CustomAlert.tsx, app/hooks/useFetch.ts, app/hooks/useWebView.ts, app/tailwind.config.js, app/utils/apis/api.ts, web/app/(personal-run)/running-session/page.tsx, web/app/group/layout.tsx, web/app/group/page.tsx, web/app/group/running/page.tsx, web/app/login/page.tsx, web/app/main/page.tsx, web/app/onboarding/page.tsx, web/components/common/ProfileImage.tsx, web/components/onBoarding/NicknameInput.tsx, web/configs/groupRouteConfig.ts, web/utils/apis/api.ts, web/utils/apis/customAxios.ts
FIX: 개인 러닝 페이지 오류 수정
- onLoadEnd와 stomp관련 에러 현상 수정
=> FIX: 개인 러닝 페이지 오류 수정

web/components/main/WelcomeCard.tsx
메인페이지 특정 뱃지 기울기,크기 수정
LuckyDay 뱃지 크기 수정, 클로버 뱃지 기울기 수정
``/web/components/main/WelcomCard.tsx``
=> fix:메인페이지 특정 뱃지 기울기,크기 수정

web/app/group/code/[...code]/page.tsx, web/components/main/CrewChallengeSection.tsx
없는 props 주석 처리
`` web/app/group/code/[...code]/page.tsx``
``web/components/main/CrewChallengeSection.tsx``
=> fix: 없는 props 주석처리

web/app/login/page.tsx
feat: 로그인 URL을 환경 변수로 변경
NEXT_PUBLIC_LOGIN_URL
=> feat: 로그인 URL을 환경 변수로 변경

web/app/login/page.tsx
=> feat: 로그인 버튼의 URL을 환경 변수로 설정

web/app/onboarding/terms/page.tsx, web/hooks/queries/useWithdraw.ts, web/utils/apis/api.ts, web/utils/apis/auth.ts, web/utils/apis/customAxios.ts
=> feat: 온보딩 페이지에 해시 토큰 처리 추가 및 API 수정

app/app/(tabs)/(home)/index.tsx
푸시 데이터 처리 로직 개선 - 특정 URL에 대해 router.replace 사용
=> feat: 푸시 데이터 처리 로직 개선 - 특정 URL에 대해 router.replace 사용

web/utils/apis/api.ts
=> fix:  러닝 강제 중단 요쳥 url 수정
